version: 2.1

executors:
  main:
    working_directory: ~/ContactRingtoneGenerator
    docker:
      - image: circleci/android:api-29
    environment:
      _JAVA_OPTIONS: -Xmx2g
      GRADLE_OPTS: -Dkotlin.compiler.execution.strategy=in-process

commands:
  execute_gradle:
    parameters:
      task_name:
        type: string
      commands:
        type: string
    steps:
      - run:
          name: <<parameters.task_name>>
          command: ./gradlew <<parameters.commands>> --max-workers=2
  update_deps:
    steps:
      - restore_cache:
          key: jars-{{ checksum "build.gradle.kts" }}-{{ checksum "app/build.gradle.kts" }}
      - execute_gradle:
          task_name: Update Dependencies
          commands: androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle.kts" }}-{{ checksum "app/build.gradle.kts" }}

jobs:
  build:
    executor: main
    steps:
      - checkout
      - update_deps
      - execute_gradle:
          task_name: Build
          commands: :app:assemble
  test:
    executor: main
    steps:
      - checkout
      - update_deps
      - execute_gradle:
          task_name: Run Tests
          commands: test
      - store_test_results:
          path: ./app/build/reports/tests/
  code_quality:
    executor: main
    steps:
      - checkout
      - update_deps
      - execute_gradle:
          task_name: Code Quality Check
          commands: :app:lint :app:spotlessCheck
      - store_artifacts:
          path: ./app/build/reports/

workflows:
  main:
    jobs:
      - build
      - test:
          requires:
            - build
      - code_quality:
          requires:
            - build